[package]
name = "pika-desktop"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
flume = "0.11"
iced = { version = "0.13", features = ["tokio"] }
pika_core = { path = "../../rust" }

[dev-dependencies]
tempfile = "3"
